<?php

$areas = array(
    'overview' => array(
        'name' => "Durham Overview",
        //'status'=>'old', 'year'=>'2021',
        'long-heading' => "Christmas Window Trails in Durham",
        'description'   => "An overview map of Durham areas with window trails, but not all the markers.",
        'umap_url' => "//umap.openstreetmap.fr/en/map/durham-christmas-windows-2021_692716",
    ),
    'belmont' => array(
        'name' => "Belmont",
        //'status'=>'old', 'year'=>'2020',
        'long-heading' => "Belmont Christmas Windows",
        'description'   => "St Mary Magdalene’s Church, in partnership with Carrville Methodist Church and other members of the community.",
        'pdf'   => 'belmont-leaflet.pdf',
        'umap_url' => "//umap.openstreetmap.fr/en/map/belmont-christmas-windows-2021_690826",
    ),
    'northend' => array(
        'name' => "North End Advent Windows",
        //'status'=>'old', 'year'=>'2021',
        'long-heading' => "North End Advent Windows",
        'description'   => "Lit up 4-10pm each day, all on display from 25th Dec till 1st Jan.",
        'image'   => 'northend-leaflet.jpg',
        //'umap_url' => "http://umap.openstreetmap.fr/en/map/north-end-advent-windows_540139",
    ),
    'shincliffe' => array(
        'name' => "Shincliffe Village Advent Windows",
        //'status'=>'old', 'year'=>'2021',
        'long-heading' => "Shincliffe Village Advent Windows",
        'description'   => "Organised by St Mary's Church.",
        'image'   => 'shincliffe-leaflet.png',
        //'umap_url' => "http://umap.openstreetmap.fr/en/map/shincliffe-advent-windows_540214",
    ),
    'gilesgate' => array(
        'name' => "Gilesgate",
        'status'=>'old', 'year'=>'2020',
        'long-heading' => "Gilesgate Christmas Trail",
        'description'   => "Lit up houses with a letter on each poster, arranged by Kings Church.",
        'image'   => 'kcd-gilesgate-leaflet.jpg',
        'umap_url' => "http://umap.openstreetmap.fr/en/map/gilesgate-christmas-trail_536914",
    ),
    'sherburn-road' => array(
        'name' => "Sherburn Road",
        'status'=>'old', 'year'=>'2020',
        'long-heading' => "Sherburn Road Christmas Trail",
        'description'   => "Lit up houses with a letter on each poster, arranged by Kings Church.",
        'image'   => 'kcd-sherburn-road-leaflet.jpg',
        'umap_url' => "//umap.openstreetmap.fr/en/map/sherburn-road-christmas-trail_536911",
    ),
    'gracechurch' => array(
        'name' => "Newton Hall etc.",
        'status'=>'old', 'year'=>'2020',
        'long-heading' => "Light in the darkness, by Grace Church.",
        'description'   => "Newton Hall, Framwellgate Moor, and Neville's Cross. Part of 'Light in the Darkness' by Grace Church",
        'image'   => 'grace-church-map.jpg',
    ),
    'elvet' => array(
        'name' => "Elvet Advent Windows",
        'status'=>'old', 'year'=>'2020',
        'long-heading' => "Elvet Residents' Association Advent Window Trail",
        'description'   => "Organised by Elvet Residents' Association. On each day of Advent, a window display will be lit up after dark.",
        'pdf'   => 'elvet-leaflet.pdf',
        'umap_url' => "http://umap.openstreetmap.fr/en/map/lvet-advent-windows_541427",
    ),
);